
name: Deploy to Azure with Bicep
on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read
          pages: write
        steps:
        - uses: actions/checkout@main
        - name: Set up Azure CLI
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
        - name: Build and deploy
          uses: Azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: ${{ secrets.AZURE_RG}}
            template: ./InfrastructureAsCode/main.bicep
            deploymentMode: 'Incremental'