name: First workflow
on:
    workflow_dispatch:
    issues:
        types: [opened]

env:
    TEXT_VAR: "Partner"

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Step 1
          run: echo "Step 1 complete $TEXT_VAR!"
        - name: Step 2
          run: echo "Step 2 complete $TEXT_VAR!"

    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        - name: Cowsays
          uses: mscoutermarsh/cowsays-action@master
          with:
            text: "Ready for prod–ship it, $TEXT_VAR!"
            color: 'magenta'